version: "2"

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  enable:
    - godot
    - errorlint
    - nolintlint
    - unconvert
    - unparam
  settings:
    govet:
      enable:
        - nilness
    staticcheck:
      checks:
        - all
        - -ST1000
