# FILL THE EMPTY VALUE ON YOUR OWN
RDB:
  Host: "localhost"
  Port: 5432
  Username: ""
  Password: ""
  DBName: "xcpc_team_reg"
  TimeZone: "" # Asia/Shanghai
Redis:
  Host: "localhost"
  Port: 6379
  Password: ""
  DB: 0
Server:
  Port: 12345
  SMTPAddr: ""
  SMTPPort: 465
  EmailSign: ""
  EmailAlias: ""
  EmailAddr: ""
  EmailPassword: ""
  EmailServer: ""
  EmailAction: # DO NOT CHANGE THE KEYS
    register: "注册账户"
    changepwd: "更改密码"
    changeemail: "更改邮箱"
    reset: "重置密码"
  EmailSubject: # DO NOT CHANGE THE KEYS
    register: "邮箱验证邮件 - 注册账户"
    changepwd: "邮箱验证邮件 - 更改密码"
    changeemail: "邮箱验证邮件 - 更改邮箱"
    reset: "邮箱验证邮件 - 重置密码"
Const:
  MaxTeamMember: 3 # In XCPC contest
  MaxTeamNameLength: 25
  UserTokenLength: 8 # The length of token in email verification and join in a team
  JWTSecret: "" # Secret uses in JWT. MUST BE STRONG ENOUGH!!!
  ValidStuIDLength: [13] # Just an example
  SchoolName: # Should be identical to the offical website
    - "School 1" # Just an example
